[general]
cpus = 6
editor = "micro"
doas = false
language = "en-US"
noconfirm = false

[aur]
build = "/home/shendisx/.cache/aura/builds"
cache = "/home/shendisx/.cache/aura/cache"
clones = "/home/shendisx/.cache/aura/packages"
hashes = "/home/shendisx/.cache/aura/hashes"
chroot = []
ignores = []
git = true
hotedit = false
shellcheck = true
diff = true
delmakedeps = false
clean = false
warn_unknowns = true
nocheck = false
skipdepcheck = false
reverse = false

[backups]
snapshots = "/home/shendisx/.cache/aura/snapshots"
automatic = true

